CREATE TABLE AGENTS (
    ID INT PRIMARY KEY,
    RESERVED_FOR VARCHAR(64) DEFAULT NULL,
    CURRENT_ORDER VARCHAR(64) DEFAULT NULL
);

INSERT INTO AGENTS (ID) VALUES (1);
INSERT INTO AGENTS (ID) VALUES (2);
INSERT INTO AGENTS (ID) VALUES (3);
INSERT INTO AGENTS (ID) VALUES (4);
INSERT INTO AGENTS (ID) VALUES (5);
INSERT INTO AGENTS (ID) VALUES (6);
INSERT INTO AGENTS (ID) VALUES (7);
INSERT INTO AGENTS (ID) VALUES (8);
INSERT INTO AGENTS (ID) VALUES (9);
INSERT INTO AGENTS (ID) VALUES (10);
INSERT INTO AGENTS (ID) VALUES (11);
INSERT INTO AGENTS (ID) VALUES (12);
INSERT INTO AGENTS (ID) VALUES (13);
INSERT INTO AGENTS (ID) VALUES (14);
INSERT INTO AGENTS (ID) VALUES (15);
INSERT INTO AGENTS (ID) VALUES (16);
INSERT INTO AGENTS (ID) VALUES (17);
INSERT INTO AGENTS (ID) VALUES (18);
