CREATE TABLE FOODS (
    ID INT PRIMARY KEY,
    RESERVED_FOR VARCHAR(64) DEFAULT NULL,
    CURRENT_ORDER VARCHAR(64) DEFAULT NULL
);

INSERT INTO FOODS (ID) VALUES (1);
INSERT INTO FOODS (ID) VALUES (2);
INSERT INTO FOODS (ID) VALUES (3);
INSERT INTO FOODS (ID) VALUES (4);
INSERT INTO FOODS (ID) VALUES (5);
INSERT INTO FOODS (ID) VALUES (6);
INSERT INTO FOODS (ID) VALUES (7);
INSERT INTO FOODS (ID) VALUES (8);
INSERT INTO FOODS (ID) VALUES (9);
INSERT INTO FOODS (ID) VALUES (10);
INSERT INTO FOODS (ID) VALUES (11);
INSERT INTO FOODS (ID) VALUES (12);
INSERT INTO FOODS (ID) VALUES (13);
INSERT INTO FOODS (ID) VALUES (14);
INSERT INTO FOODS (ID) VALUES (15);
INSERT INTO FOODS (ID) VALUES (16);
INSERT INTO FOODS (ID) VALUES (17);
INSERT INTO FOODS (ID) VALUES (18);
INSERT INTO FOODS (ID) VALUES (19);
INSERT INTO FOODS (ID) VALUES (20);
INSERT INTO FOODS (ID) VALUES (21);
INSERT INTO FOODS (ID) VALUES (22);
INSERT INTO FOODS (ID) VALUES (23);
INSERT INTO FOODS (ID) VALUES (24);
INSERT INTO FOODS (ID) VALUES (25);
